const formInputFields = [
  {
    htmlFor: 'business_code',
    label: 'Business Code',
    type: 'select',
    data: [{ value: 'null', label: 'null' }],
    placeholder: 'Your business code',
    required: true,
  },
  {
    htmlFor: 'cust_number',
    label: 'Customer Number',
    type: 'select',
    searchable: true,
    data: [{ value: 'null', label: 'null' }],
    placeholder: 'Customer Number',
    required: true,
  },
  {
    htmlFor: 'business_year',
    type: 'number',
    label: 'Business Year',
    placeholder: 'Business Year (YYYY)',
    required: true,
  },
  {
    htmlFor: 'doc_id',
    label: 'Document ID',
    placeholder: 'Document ID',
    required: true,
  },
  {
    htmlFor: 'invoice_currency',
    label: 'Invoice Currency',
    placeholder: 'Invoice Currency (₹)',
    type: 'number',
    required: false,
  },
  {
    htmlFor: 'document_type',
    label: 'Document Type',
    placeholder: 'Document Type',
    required: true,
  },
  {
    htmlFor: 'posting_id',
    label: 'Posting ID',
    placeholder: 'Posting ID',
    required: true,
  },
  {
    htmlFor: 'total_open_amount',
    label: 'Total Open Amount',
    placeholder: '0',
    type: 'number',
    required: false,
  },
  {
    htmlFor: 'cust_payment_terms',
    label: 'Customer Payment Terms',
    placeholder: '',
    required: true,
  },
  {
    htmlFor: 'invoice_id',
    label: 'Invoice ID',
    placeholder: 'N/A',
    required: true,
  },
];

const formDateFields = [
  {
    htmlFor: 'clear_date',
    label: 'Clear Date',
    required: true,
    placeholder: 'Pick a Clear Date',
    type: 'db_date',
  },
  {
    htmlFor: 'posting_date',
    label: 'Posting Date',
    required: true,
    placeholder: 'Pick a Clear Date',
    type: 'db_date',
  },
  {
    htmlFor: 'document_create_date',
    label: 'Document Create Date',
    required: true,
    placeholder: 'Pick a Document Create Date',
    type: 'db_date',
  },
  {
    htmlFor: 'due_in_date',
    label: 'Due Date',
    required: true,
    placeholder: 'Pick a Due Date',
    type: 'db_date',
  },
  {
    htmlFor: 'baseline_create_date',
    label: 'Baseline Create Date',
    required: true,
    placeholder: 'Pick a Baseline Create Date',
    type: 'db_date',
  },
];

const defaultTableSchema = {
  sl_no: null,
  business_code: null,
  cust_number: '200020431',
  clear_date: '2022-3-1',
  business_year: null,
  doc_id: null,
  posting_date: '2022-3-1',
  document_create_date: '2022-3-2',
  document_create_date1: null,
  due_in_date: '2022-3-19',
  invoice_currency: null,
  document_type: null,
  posting_id: null,
  area_business: null,
  total_open_amount: null,
  baseline_create_date: '2022-3-15',
  cust_payment_terms: null,
  invoice_id: null,
  isOpen: null,
  aging_bucket: null,
  is_deleted: null,
};

export { formInputFields, formDateFields, defaultTableSchema };
